# Generated by Django 4.2.7 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('concert', 'Concert'), ('stage_event', 'Stage Event'), ('educational', 'Educational'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
