# Generated by Django 4.2.7 on 2025-05-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_event_options_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: apps.get_model('mainapp', 'Department').objects.bulk_create([
            apps.get_model('mainapp', 'Department')(name='Faculty of Engineering & Technology', code='FET'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Computer Science & Applications', code='FCSA'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Management Studies', code='FMS'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Architecture', code='FARCH'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Commerce', code='FCOM'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Science', code='FSCI'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Pharmacy', code='FPHARM'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Medicine', code='FMED'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Dental Sciences', code='FDS'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Nursing', code='FNUR'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Physiotherapy', code='FPHYS'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Agriculture', code='FAGRI'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Fine Arts', code='FFA'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Law', code='FLAW'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Library Sciences', code='FLS'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Social Work', code='FSW'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Ayurveda', code='FAYU'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Homeopathy', code='FHOM'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Applied Sciences', code='FAS'),
            apps.get_model('mainapp', 'Department')(name='Faculty of Research Studies', code='FRS')
        ])),
        migrations.RunPython(lambda apps, schema_editor: None, reverse_code=lambda apps, schema_editor: apps.get_model('mainapp', 'Department').objects.all().delete())
    ]
