# Generated by Django 4.2.7 on 2025-05-21 20:38

from django.db import migrations
from django.contrib.auth.hashers import make_password
import random

def generate_users(apps, schema_editor):
    Department = apps.get_model('mainapp', 'Department')
    CustomUser = apps.get_model('mainapp', 'CustomUser')
    departments = list(Department.objects.all())

    # Create 30 students
    for i in range(1, 31):
        dept = random.choice(departments)
        CustomUser.objects.create(
            username=f'student{i}',
            email=f'student{i}@unishowtime.com',
            password=make_password('Student@123'),
            role='student',
            enrollment_no=f'ST{str(i).zfill(4)}',
            department=dept,
            is_active=True
        )

    # Create 10 teachers
    for i in range(1, 11):
        dept = random.choice(departments)
        CustomUser.objects.create(
            username=f'teacher{i}',
            email=f'teacher{i}@unishowtime.com',
            password=make_password('Teacher@123'),
            role='admin',
            department=dept,
            is_active=True
        )

    # Create 5 superadmins
    for i in range(1, 6):
        CustomUser.objects.create(
            username=f'admin{i}',
            email=f'admin{i}@unishowtime.com',
            password=make_password('Admin@123'),
            role='superadmin',
            is_active=True,
            is_staff=True,
            is_superuser=True
        )

def reverse_users(apps, schema_editor):
    CustomUser = apps.get_model('mainapp', 'CustomUser')
    CustomUser.objects.filter(
        username__in=[
            *[f'student{i}' for i in range(1, 31)],
            *[f'teacher{i}' for i in range(1, 11)],
            *[f'admin{i}' for i in range(1, 6)]
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_add_departments'),
    ]

    operations = [
        migrations.RunPython(generate_users, reverse_users),
    ]
